import subprocess

execution_times = 30
"""
for i in range(10):
    subprocess.call("python distance_check.py CENSUS MLPC 1000 L1")

exit(1)
"""
for i in range(30):
    
    subprocess.call("python random_reverse.py CENSUS_age SVM 1000")
    subprocess.call("python random_reverse.py CENSUS_age MLPC 200")
    subprocess.call("python random_reverse.py CENSUS_age RF 100")
    subprocess.call("python random_reverse.py CENSUS_race SVM 5000")
    subprocess.call("python random_reverse.py CENSUS_race MLPC 1000")
    subprocess.call("python random_reverse.py CENSUS_race RF 2000")
    subprocess.call("python random_reverse.py GERMAN_age SVM 1000")
    subprocess.call("python random_reverse.py GERMAN_age MLPC 200")
    subprocess.call("python random_reverse.py GERMAN_age RF 200")
    
    subprocess.call("python random_reverse.py CENSUS_sex SVM 20000")
    subprocess.call("python random_reverse.py CENSUS_sex MLPC 2000")
    subprocess.call("python random_reverse.py CENSUS_sex RF 500")
    subprocess.call("python random_reverse.py BANK_age SVM 2000")
    subprocess.call("python random_reverse.py BANK_age MLPC 500")
    subprocess.call("python random_reverse.py BANK_age RF 300")
    subprocess.call("python random_reverse.py GERMAN_sex SVM 40000")
    subprocess.call("python random_reverse.py GERMAN_sex MLPC 200")
    subprocess.call("python random_reverse.py GERMAN_sex RF 300")
    """
    subprocess.call("python random_reverse.py GERMAN_age SVM 1000")
    subprocess.call("python random_reverse.py GERMAN_age MLPC 200")
    subprocess.call("python random_reverse.py GERMAN_age RF 200")
    """
    """
    #for dataset in ["CENSUS_age", "CENSUS_race", "CENSUS_sex", "BANK_age", "GERMAN_sex", "GERMAN_age"]:
    #subprocess.call("python random_majority.py CENSUS SVM 20000")
    subprocess.call("python random_majority.py CENSUS_sex MLPC 2000")
    #subprocess.call("python random_majority.py CENSUS RF 500")
    #subprocess.call("python random_majority.py BANK SVM 2000")
    subprocess.call("python random_majority.py BANK_age MLPC 500")
    #subprocess.call("python random_majority.py BANK RF 300")
    #subprocess.call("python random_majority.py GERMAN SVM 40000")
    subprocess.call("python random_majority.py GERMAN_sex MLPC 200")
    #subprocess.call("python random_majority.py GERMAN RF 300")
    
    #subprocess.call("python random_majority.py CENSUS_age SVM 1000")
    subprocess.call("python random_majority.py CENSUS_age MLPC 200")
    #subprocess.call("python random_majority.py CENSUS_age RF 100")
    #subprocess.call("python random_majority.py CENSUS_race SVM 5000")
    subprocess.call("python random_majority.py CENSUS_race MLPC 1000")
    #subprocess.call("python random_majority.py CENSUS_race RF 2000")
    #subprocess.call("python random_majority.py GERMAN_age SVM 1000")
    subprocess.call("python random_majority.py GERMAN_age MLPC 200")
    #subprocess.call("python random_majority.py GERMAN_age RF 200")
    """
    
    """
    subprocess.call("python random_random.py CENSUS_age SVM 1000")
    subprocess.call("python random_random.py CENSUS_age MLPC 200")
    subprocess.call("python random_random.py CENSUS_age RF 100")
    subprocess.call("python random_random.py CENSUS_race SVM 5000")
    subprocess.call("python random_random.py CENSUS_race MLPC 1000")
    subprocess.call("python random_random.py CENSUS_race RF 2000")
    subprocess.call("python random_random.py GERMAN_age SVM 1000")
    subprocess.call("python random_random.py GERMAN_age MLPC 200")
    subprocess.call("python random_random.py GERMAN_age RF 200")
    
    subprocess.call("python pair_0.py CENSUS_age SVM 1000")
    subprocess.call("python pair_0.py CENSUS_age MLPC 200")
    subprocess.call("python pair_0.py CENSUS_age RF 100")
    subprocess.call("python pair_0.py CENSUS_race SVM 5000")
    subprocess.call("python pair_0.py CENSUS_race MLPC 1000")
    subprocess.call("python pair_0.py CENSUS_race RF 2000")
    subprocess.call("python pair_0.py GERMAN_age SVM 1000")
    subprocess.call("python pair_0.py GERMAN_age MLPC 200")
    subprocess.call("python pair_0.py GERMAN_age RF 200")
    
    subprocess.call("python pair_majority.py CENSUS_age SVM 1000")
    subprocess.call("python pair_majority.py CENSUS_age MLPC 200")
    subprocess.call("python pair_majority.py CENSUS_age RF 100")
    subprocess.call("python pair_majority.py CENSUS_race SVM 5000")
    subprocess.call("python pair_majority.py CENSUS_race MLPC 1000")
    subprocess.call("python pair_majority.py CENSUS_race RF 2000")
    subprocess.call("python pair_majority.py GERMAN_age SVM 1000")
    subprocess.call("python pair_majority.py GERMAN_age MLPC 200")
    subprocess.call("python pair_majority.py GERMAN_age RF 200")
    
    subprocess.call("python pair_random.py CENSUS_age SVM 1000")
    subprocess.call("python pair_random.py CENSUS_age MLPC 200")
    subprocess.call("python pair_random.py CENSUS_age RF 100")
    subprocess.call("python pair_random.py CENSUS_race SVM 5000")
    subprocess.call("python pair_random.py CENSUS_race MLPC 1000")
    subprocess.call("python pair_random.py CENSUS_race RF 2000")
    subprocess.call("python pair_random.py GERMAN_age SVM 1000")
    subprocess.call("python pair_random.py GERMAN_age MLPC 200")
    subprocess.call("python pair_random.py GERMAN_age RF 200")
    
    subprocess.call("python 0_0.py CENSUS_age SVM 1000")
    subprocess.call("python 0_0.py CENSUS_age MLPC 200")
    subprocess.call("python 0_0.py CENSUS_age RF 100")
    subprocess.call("python 0_0.py CENSUS_race SVM 5000")
    subprocess.call("python 0_0.py CENSUS_race MLPC 1000")
    subprocess.call("python 0_0.py CENSUS_race RF 2000")
    subprocess.call("python 0_0.py GERMAN_age SVM 1000")
    subprocess.call("python 0_0.py GERMAN_age MLPC 200")
    subprocess.call("python 0_0.py GERMAN_age RF 200")
    
    subprocess.call("python random_0.py CENSUS_age SVM 1000")
    subprocess.call("python random_0.py CENSUS_age MLPC 200")
    subprocess.call("python random_0.py CENSUS_age RF 100")
    subprocess.call("python random_0.py CENSUS_race SVM 5000")
    subprocess.call("python random_0.py CENSUS_race MLPC 1000")
    subprocess.call("python random_0.py CENSUS_race RF 2000")
    subprocess.call("python random_0.py GERMAN_age SVM 1000")
    subprocess.call("python random_0.py GERMAN_age MLPC 200")
    subprocess.call("python random_0.py GERMAN_age RF 200")
    
    subprocess.call("python random_majority.py CENSUS_age SVM 1000")
    subprocess.call("python random_majority.py CENSUS_age MLPC 200")
    subprocess.call("python random_majority.py CENSUS_age RF 100")
    subprocess.call("python random_majority.py CENSUS_race SVM 5000")
    subprocess.call("python random_majority.py CENSUS_race MLPC 1000")
    subprocess.call("python random_majority.py CENSUS_race RF 2000")
    subprocess.call("python random_majority.py GERMAN_age SVM 1000")
    subprocess.call("python random_majority.py GERMAN_age MLPC 200")
    subprocess.call("python random_majority.py GERMAN_age RF 200")
    """
    """  
    subprocess.call("python random_random.py CENSUS SVM 20000")
    subprocess.call("python random_random.py CENSUS MLPC 2000")
    subprocess.call("python random_random.py CENSUS RF 500")
    subprocess.call("python random_random.py BANK SVM 2000")
    subprocess.call("python random_random.py BANK MLPC 500")
    subprocess.call("python random_random.py BANK RF 300")
    subprocess.call("python random_random.py GERMAN SVM 40000")
    subprocess.call("python random_random.py GERMAN MLPC 200")
    subprocess.call("python random_random.py GERMAN RF 300")
    
    subprocess.call("python pair_0.py CENSUS SVM 20000")
    subprocess.call("python pair_0.py CENSUS MLPC 2000")
    subprocess.call("python pair_0.py CENSUS RF 500")
    subprocess.call("python pair_0.py BANK SVM 2000")
    subprocess.call("python pair_0.py BANK MLPC 500")
    subprocess.call("python pair_0.py BANK RF 300")
    subprocess.call("python pair_0.py GERMAN SVM 40000")
    subprocess.call("python pair_0.py GERMAN MLPC 200")
    subprocess.call("python pair_0.py GERMAN RF 300")

    
    subprocess.call("python pair_majority.py CENSUS SVM 20000")
    subprocess.call("python pair_majority.py CENSUS MLPC 2000")
    subprocess.call("python pair_majority.py CENSUS RF 500")
    subprocess.call("python pair_majority.py BANK SVM 2000")
    subprocess.call("python pair_majority.py BANK MLPC 500")
    subprocess.call("python pair_majority.py BANK RF 300")
    subprocess.call("python pair_majority.py GERMAN SVM 40000")
    subprocess.call("python pair_majority.py GERMAN MLPC 200")
    subprocess.call("python pair_majority.py GERMAN RF 300")
    
    subprocess.call("python pair_random.py CENSUS SVM 20000")
    subprocess.call("python pair_random.py CENSUS MLPC 2000")
    subprocess.call("python pair_random.py CENSUS RF 500")
    subprocess.call("python pair_random.py BANK SVM 2000")
    subprocess.call("python pair_random.py BANK MLPC 500")
    subprocess.call("python pair_random.py BANK RF 300")
    subprocess.call("python pair_random.py GERMAN SVM 40000")
    subprocess.call("python pair_random.py GERMAN MLPC 200")
    subprocess.call("python pair_random.py GERMAN RF 300")

    subprocess.call("python 0_0.py CENSUS SVM 20000")
    subprocess.call("python 0_0.py CENSUS MLPC 2000")
    subprocess.call("python 0_0.py CENSUS RF 500")
    subprocess.call("python 0_0.py BANK SVM 2000")
    subprocess.call("python 0_0.py BANK MLPC 500")
    subprocess.call("python 0_0.py BANK RF 300")
    subprocess.call("python 0_0.py GERMAN SVM 40000")
    subprocess.call("python 0_0.py GERMAN MLPC 200")
    subprocess.call("python 0_0.py GERMAN RF 300")
    
    subprocess.call("python random_0.py CENSUS SVM 20000")
    subprocess.call("python random_0.py CENSUS MLPC 2000")
    subprocess.call("python random_0.py CENSUS RF 500")
    subprocess.call("python random_0.py BANK SVM 2000")
    subprocess.call("python random_0.py BANK MLPC 500")
    subprocess.call("python random_0.py BANK RF 300")
    subprocess.call("python random_0.py GERMAN SVM 40000")
    subprocess.call("python random_0.py GERMAN MLPC 200")
    subprocess.call("python random_0.py GERMAN RF 300")
    
    subprocess.call("python random_majority.py CENSUS SVM 20000")
    subprocess.call("python random_majority.py CENSUS MLPC 2000")
    subprocess.call("python random_majority.py CENSUS RF 500")
    subprocess.call("python random_majority.py BANK SVM 2000")
    subprocess.call("python random_majority.py BANK MLPC 500")
    subprocess.call("python random_majority.py BANK RF 300")
    subprocess.call("python random_majority.py GERMAN SVM 40000")
    subprocess.call("python random_majority.py GERMAN MLPC 200")
    subprocess.call("python random_majority.py GERMAN RF 300")

"""